### ISSUE TITLE
"Maximum object expansion depth exceeded" when importing in Foundry v11

### ISSUE THREAD

**Issue by dmarcuse** [dmarcuse/fvtt-adventure-bundler#9]
Occasionally, importing a bundle in Foundry v11 with version 0.2.3 fails with a vague error which occurs on the _server_ side:

```
FoundryVTT | 2023-06-18 17:03:29 | [error] Maximum object expansion depth exceeded
Error: Maximum object expansion depth exceeded
    at _expand (file:///home/dana/foundry/stable/bin/resources/app/common/utils/helpers.mjs:257:29)
    at _expand (file:///home/dana/foundry/stable/bin/resources/app/common/utils/helpers.mjs:263:32)
    at file:///home/dana/foundry/stable/bin/resources/app/common/utils/helpers.mjs:259:55
    at Array.map (<anonymous>)
    at _expand (file:///home/dana/foundry/stable/bin/resources/app/common/utils/helpers.mjs:259:46)
    at _expand (file:///home/dana/foundry/stable/bin/resources/app/common/utils/helpers.mjs:263:32)
    at file:///home/dana/foundry/stable/bin/resources/app/common/utils/helpers.mjs:259:55
    at Array.map (<anonymous>)
    at _expand (file:///home/dana/foundry/stable/bin/resources/app/common/utils/helpers.mjs:259:46)
    at _expand (file:///home/dana/foundry/stable/bin/resources/app/common/utils/helpers.mjs:263:32)
```

This seems to be a recursion issue, and is reproducible when trying to import the same bundle.

**Comment by dmarcuse** [comment]
This seems to be fixed as of [Foundry release 11.306](https://foundryvtt.com/releases/11.306).
